name: Copy Docs to GitHub Pages
on:
  push:
    branches:
      - main 

jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: TestOrgLeonB/testorgleonb.github.io
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch repositories
        id: fetch_repos
        run: |
          repos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/TestOrgLeonB/repos" | jq -r '.[] | select(.name != "testorgleonb.github.io") | .name')
          echo "::set-output name=repos::$repos"

      - name: Checkout and copy docs from each repository
        run: |
          for repo in ${{ steps.fetch_repos.outputs.repos }}; do
            echo "Processing $repo"
            # Checkout repository
            git clone --depth 1 --branch main https://github.com/TestOrgLeonB/$repo.git $repo
            # Copy doc.md
            cp $repo/doc.md $repo-doc.md
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
