name: Copy Docs to GitHub Pages
on:
  schedule:
    - cron: "*/3 * * * *"

permissions: write-all

jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -r requirements.txt; 



      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: TestOrgLeonB/testorgleonb.github.io
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch repositories
        id: fetch_repos
        run: |
          python fetch_repos.py TestOrgLeonB ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

